FROM php:8.2-fpm

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
      apt-utils \
      libzip-dev \
      zip unzip \
      libpq-dev && \
      docker-php-ext-install pdo pdo_pgsql && \
      docker-php-ext-install zip && \
      docker-php-ext-install sockets && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


