version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
    container_name: import_export_nginx

  php: &php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile.local
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    container_name: import_export_php

  postgres:
    image: library/postgres:12.3
    volumes:
      - ./pgsql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGGSSENCMODE=disable
    ports:
      - "5432:5432"
    restart: unless-stopped
    container_name: import_export_postgres

  queue:
    <<: *php
    command: [ 'php', 'artisan', 'queue:work' ]
    depends_on:
      - postgres
    container_name: import_export_queue
